name: E2E test
on:
  pull_request:
jobs:
  e2e:
    timeout-minutes: 20
    name: E2E tests (${{ matrix.shard }}/${{ strategy.job-total }})
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:12.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: calendso
        ports:
          - 5432:5432
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4, 5]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/dangerous-git-checkout
      - run: echo 'NODE_OPTIONS="--max_old_space_size=4096"' >> $GITHUB_ENV
      - uses: ./.github/actions/yarn-install
      - uses: ./.github/actions/yarn-playwright-install
      - run: |
          cp .env.example .env
          sed -i 's;DATABASE_URL=.*;DATABASE_URL="postgresql://postgres:@localhost:5432/calendso";g' .env
          sed -i "s;NEXTAUTH_SECRET=.*;NEXTAUTH_SECRET=\"$(openssl rand -base64 32)\";g" .env
          sed -i "s;CALENDSO_ENCRYPTION_KEY=.*;CALENDSO_ENCRYPTION_KEY=\"$(openssl rand -base64 24)\";g" .env
          sed -i "s;EMAIL_SERVER_HOST=.*;;g" .env
      - uses: ./.github/actions/cache-db
      - uses: ./.github/actions/cache-build
      - name: Run Tests
        run: yarn e2e --shard=${{ matrix.shard }}/${{ strategy.job-total }}
        env:
          DEPLOYSENTINEL_API_KEY: ${{ secrets.DEPLOYSENTINEL_API_KEY }}
      - name: Upload Test Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-results-${{ matrix.shard }}_${{ strategy.job-total }}
          path: test-results
